### ISSUE TITLE
tiller not yet running, waiting ...

### ISSUE THREAD

**Issue by KrishnaPG** [data-mill-cloud/data-mill#9]
On Ubuntu 18, getting the below error with run install:
````

linux-amd64/
linux-amd64/tiller
linux-amd64/helm
linux-amd64/LICENSE
linux-amd64/README.md
Installing Tiller
serviceaccount/tiller created
clusterrolebinding.rbac.authorization.k8s.io/tiller created
Creating /root/.helm
Creating /root/.helm/repository
Creating /root/.helm/repository/cache
Creating /root/.helm/repository/local
Creating /root/.helm/plugins
Creating /root/.helm/starters
Creating /root/.helm/cache/archive
Creating /root/.helm/repository/repositories.yaml
Adding stable repo with URL: https://kubernetes-charts.storage.googleapis.com
Adding local repo with URL: http://127.0.0.1:8879/charts
$HELM_HOME has been configured at /root/.helm.
Error: error installing: the server could not find the requested resource
tiller not yet running, waiting...
tiller not yet running, waiting...
tiller not yet running, waiting...
tiller not yet running, waiting...
tiller not yet running, waiting...
tiller not yet running, waiting...
tiller not yet running, waiting...
tiller not yet running, waiting...
tiller not yet running, waiting...

````
There it keeps waiting.

The run command was launched as below:
````
./run.sh -l -i -f ./flavours/ds_flavour.yaml
````
The flavour file is as below:
````
project:
  k8s_namespace: data-mill
  proxy_port: 8088
  flavour: minio, pachyderm, druid, superset, dask, seldon, jupyterhub, mlflow, grafana
  # k8s default config, can be overwritten with -t filename
  k8s_default_config: default_uc.yaml
  # component default config, can be overwritten with -f filename
  component_default_config: config.yaml
  # set the data folder
  data_folder: data
````
